In [1]:
import numpy as np 
import torch 
import torch.nn as nn 


### Model


In [11]:
class LNN(nn.Module):
    
    
    def __init__(self,input,output):   
        super(LNN, self).__init__()
        self.linear = nn.Linear(input, output)
        
    def forward(self, x):
        out = self.linear(x)
        return out
    
    
    # backward is handled automatically by PyTorch's autograd
                        
        

### DATA

In [12]:
np.random.seed(0)
X = np.random.randn(100, 2)
true_W = np.array([[3],[5]])
true_b = 10
Y = X @ true_W + true_b + 0.2*np.random.randn(100, 1)   # add slight noise

X = torch.tensor(X, dtype=torch.float32)
Y = torch.tensor(Y, dtype=torch.float32)

In [13]:
model = LNN(2,1)  # 2 inputs, 1 outputs


epochs = 2000
lr = 0.01

model = LNN(2,1)


print(model.linear.weight.data)
print(model.linear.bias.data)


criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=lr)


for epoch in range(epochs):

    
    out = model.forward(X)
    
    loss = criterion(out,Y)
    
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    
    if (epoch+1) % 200 == 0:
        print(f"Epoch {epoch+1}/{epochs}  Loss = {loss:.4f}")
        
print("\nLearned W:\n", model.linear.weight.data)
print("Learned b:\n", model.linear.bias.data)


tensor([[ 0.6247, -0.0683]])
tensor([0.2478])
Epoch 200/2000  Loss = 0.0601
Epoch 400/2000  Loss = 0.0356
Epoch 600/2000  Loss = 0.0356
Epoch 800/2000  Loss = 0.0356
Epoch 1000/2000  Loss = 0.0356
Epoch 1200/2000  Loss = 0.0356
Epoch 1400/2000  Loss = 0.0356
Epoch 1600/2000  Loss = 0.0356
Epoch 1800/2000  Loss = 0.0356
Epoch 2000/2000  Loss = 0.0356

Learned W:
 tensor([[3.0221, 4.9892]])
Learned b:
 tensor([9.9897])
